app = "iskin-ra"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
app = "python ra_bot_gpt.py"
