app = "iskin-ra"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
    
[experimental]
  allowed_public_ports = [80, 443]
  auto_rollback = true

[processes]
  web = "uvicorn ra_bot_gpt:app --host 0.0.0.0 --port $PORT"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["web"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[mounts]
  source = "ra_memory"
  destination = "/mnt/ra_memory"
