name: Fly Deploy via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Build flyctl Docker image
        run: docker build -f Dockerfile.flyctl -t flyctl-container .

      - name: Deploy to Fly.io
        run: |
          docker run --rm -e FLY_API_TOKEN=${{ secrets.FLY_API_TOKEN }} flyctl-container deploy --remote-only
